import { LetterToKana } from '../scenes/shared/types'

const letterToHiragana: LetterToKana = {
    a: 'あ',
    i: 'い',
    u: 'う',
    e: 'え',
    o: 'お',
    ka: 'か',
    ki: 'き',
    ku: 'く',
    ke: 'け',
    ko: 'こ',
    sa: 'さ',
    shi: 'し',
    su: 'す',
    se: 'せ',
    so: 'そ',
    ta: 'た',
    chi: 'ち',
    tsu: 'つ',
    te: 'て',
    to: 'と',
    na: 'な',
    ni: 'に',
    nu: 'ぬ',
    ne: 'ね',
    no: 'の',
    ha: 'は',
    hi: 'ひ',
    fu: 'ふ',
    he: 'へ',
    ho: 'ほ',
    ma: 'ま',
    mi: 'み',
    mu: 'む',
    me: 'め',
    mo: 'も',
    ya: 'や',
    yu: 'ゆ',
    yo: 'よ',
    ra: 'ら',
    ri: 'り',
    ru: 'る',
    re: 'れ',
    ro: 'ろ',
    wa: 'わ',
    wo: 'を',
    kya: 'きゃ',
    kyu: 'きゅ',
    kyo: 'きょ',
    sha: 'しょ',
    shu: 'しゅ',
    sho: 'しょ',
    cha: 'ちゃ',
    chu: 'ちゅ',
    cho: 'ちょ',
    nya: 'にゃ',
    nyu: 'にゅ',
    nyo: 'にょ',
    hya: 'ひゃ',
    hyu: 'ひゅ',
    hyo: 'ひょ',
    mya: 'みゃ',
    myu: 'みゅ',
    myo: 'みょ',
    rya: 'りゃ',
    ryu: 'りゅ',
    ryo: 'りょ',
    ga: 'が',
    gi: 'ぎ',
    gu: 'ぐ',
    ge: 'げ',
    go: 'ご',
    za: 'ざ',
    ji: 'じ',
    zu: 'ず',
    ze: 'ぜ',
    zo: 'ぞ',
    da: 'だ',
    di: 'ぢ',
    du: 'づ',
    de: 'で',
    do: 'ど',
    ba: 'ば',
    bi: 'び',
    bu: 'ぶ',
    be: 'べ',
    bo: 'ぼ',
    pa: 'ぱ',
    pi: 'ぴ',
    pu: 'ぷ',
    pe: 'ぺ',
    po: 'ぽ',
    nn: 'ん',
    gya: 'ぎゃ',
    gyu: 'ぎゅ',
    gyo: 'ぎょ',
    ja: 'じゃ',
    ju: 'じゅ',
    jo: 'じょ',
    dya: 'ぢゃ',
    dyu: 'ぢゅ',
    dyo: 'ぢょ',
    bya: 'びゃ',
    byu: 'びゅ',
    byo: 'びょ',
    pya: 'ぴゃ',
    pyu: 'ぴゅ',
    pyo: 'ぴょ',

}

const letterToKatakana: LetterToKana = {
    'a': 'ア',
    'i': 'イ',
    'u': 'ウ',
    'e': 'エ',
    'o': 'オ',
    'ka': 'カ',
    'ki': 'キ',
    'ku': 'ク',
    'ke': 'ケ',
    'ko': 'コ',
    'sa': 'サ',
    'shi': 'シ',
    'su': 'ス',
    'se': 'セ',
    'so': 'ソ',
    'ta': 'タ',
    'chi': 'チ',
    'tsu': 'ツ',
    'te': 'テ',
    'to': 'ト',
    'na': 'ナ',
    'ni': 'ニ',
    'nu': 'ヌ',
    'ne': 'ネ',
    'no': 'ノ',
    'ha': 'ハ',
    'hi': 'ヒ',
    'fu': 'フ',
    'he': 'ヘ',
    'ho': 'ホ',
    'ma': 'マ',
    'mi': 'ミ',
    'mu': 'ム',
    'me': 'メ',
    'mo': 'モ',
    'ya': 'ヤ',
    'yu': 'ユ',
    'yo': 'ヨ',
    'ra': 'ラ',
    'ri': 'リ',
    'ru': 'ル',
    're': 'レ',
    'ro': 'ロ',
    'wa': 'ワ',
    'wo': 'ヲ',
    'kya': 'キャ',
    'kyu': 'キュ',
    'kyo': 'キョ',
    'sha': 'シャ',
    'shu': 'シュ',
    'sho': 'ショ',
    'cha': 'チャ',
    'chu': 'チュ',
    'cho': 'チョ',
    'nya': 'ニャ',
    'nyu': 'ニュ',
    'nyo': 'ニョ',
    'hya': 'ヒャ',
    'hyu': 'ヒュ',
    'hyo': 'ヒョ',
    'mya': 'ミャ',
    'myu': 'ミュ',
    'myo': 'ミョ',
    'rya': 'リャ',
    'ryu': 'リュ',
    'ryo': 'リョ',
    'ga': 'ガ',
    'gi': 'ギ',
    'gu': 'グ',
    'ge': 'ゲ',
    'go': 'ゴ',
    'za': 'ザ',
    'ji': 'ジ',
    'zu': 'ズ',
    'ze': 'ゼ',
    'zo': 'ゾ',
    'da': 'ダ',
    'di': 'ヂ',
    'du': 'ヅ',
    'de': 'デ',
    'do': 'ド',
    'ba': 'バ',
    'bi': 'ビ',
    'bu': 'ブ',
    'be': 'ベ',
    'bo': 'ボ',
    'pa': 'パ',
    'pi': 'ピ',
    'pu': 'プ',
    'pe': 'ペ',
    'po': 'ポ',
    'nn': 'ン',
    'gya': 'ギャ',
    'gyu': 'ギュ',
    'gyo': 'ギョ',
    'ja': 'ジャ',
    'ju': 'ジュ',
    'jo': 'ジョ',
    'dya': 'ヂャ',
    'dyu': 'ヂュ',
    'dyo': 'ヂョ',
    'bya': 'ビャ',
    'byu': 'ビュ',
    'byo': 'ビョ',
    'pya': 'ピャ',
    'pyu': 'ピュ',
    'pyo': 'ピョ',

}

const convertToKana = (romaji: string): { hiragana: string, katakana: string } => {

    let finalHiraganaString = '';
    let finalKatakanaString = '';

    for (let i = 0; i < romaji.length; i++) {
        let chunk = romaji.slice(i, i + 3); //sliding window
        let addToFinalHiraganaString = ''
        let addToFinalKatakanaString = ''

        for (let j = 0; j < chunk.length; j++) {

            let chunkSection = chunk.slice(0, j + 1);

            if (chunkSection in letterToHiragana) {

                addToFinalHiraganaString = addToFinalHiraganaString.slice(j) + letterToHiragana[chunkSection];
                addToFinalKatakanaString = addToFinalKatakanaString.slice(j) + letterToKatakana[chunkSection];
                i = i + chunkSection.length - 1;

            } else {
                addToFinalHiraganaString = addToFinalHiraganaString.slice(0, j) + chunk.slice(j, 1)
                addToFinalKatakanaString = addToFinalKatakanaString.slice(0, j) + chunk.slice(j, 1)
            }
        }

        finalHiraganaString = finalHiraganaString + addToFinalHiraganaString;
        finalKatakanaString = finalKatakanaString + addToFinalKatakanaString;

    }

    return { "hiragana": finalHiraganaString, "katakana": finalKatakanaString };

}

export default convertToKana